// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	discordConnect: (params: DiscordConnectParams) => __TAURI_INVOKE<null>("discord_connect", { params }),
	discordDisconnect: () => __TAURI_INVOKE<null>("discord_disconnect"),
	discordSetActivity: (params: ActivityInput) => __TAURI_INVOKE<null>("discord_set_activity", { params }),
	discordClearActivity: () => __TAURI_INVOKE<null>("discord_clear_activity"),
	getDeviceCode: () => __TAURI_INVOKE<DcfAuthResponse>("get_device_code"),
	restoreSession: () => __TAURI_INVOKE<{
	id: UserId,
	login: string,
	displayName: string,
	description: string,
	profileImageUrl: string,
	broadcasterType: BroadcasterType,
	createdAt: string,
} | null>("restore_session"),
	revokeSession: () => __TAURI_INVOKE<null>("revoke_session"),
	subscribe: (params: SubscribeParams) => __TAURI_INVOKE<null>("subscribe", { params }),
	unsubscribe: (params: SubscribeParams) => __TAURI_INVOKE<null>("unsubscribe", { params }),
	getFollowedStreams: () => __TAURI_INVOKE<Stream[]>("get_followed_streams"),
	getStreams: (params: GetStreamsParams) => __TAURI_INVOKE<PaginatedResponse<Stream>>("get_streams", { params }),
	getStreamsFromIds: (params: GetStreamsFromIdsParams) => __TAURI_INVOKE<Stream[]>("get_streams_from_ids", { params }),
	createStreamMarker: (params: CreateStreamMarkerParams) => __TAURI_INVOKE<null>("create_stream_marker", { params }),
	getUsers: (params: GetUsersParams) => __TAURI_INVOKE<User[]>("get_users", { params }),
	searchChannels: (params: SearchChannelsParams) => __TAURI_INVOKE<SearchChannel[]>("search_channels", { params }),
	searchCategories: (params: SearchCategoriesParams) => __TAURI_INVOKE<Category[]>("search_categories", { params }),
	sendShoutout: (params: SendShoutoutParams) => __TAURI_INVOKE<null>("send_shoutout", { params }),
	sendChatMessage: (params: SendChatMessageParams) => __TAURI_INVOKE<SendMessageResult>("send_chat_message", { params }),
	sendChatAnnouncement: (params: SendChatAnnouncementParams) => __TAURI_INVOKE<null>("send_chat_announcement", { params }),
	updateChatSettings: (params: UpdateChatSettingsParams) => __TAURI_INVOKE<null>("update_chat_settings", { params }),
	updateUserChatColor: (params: UpdateUserChatColorParams) => __TAURI_INVOKE<null>("update_user_chat_color", { params }),
	getUserEmotes: () => __TAURI_INVOKE<UserEmote[]>("get_user_emotes"),
	getGlobalEmotes: () => __TAURI_INVOKE<Emote[]>("get_global_emotes"),
	getGlobalChatBadges: () => __TAURI_INVOKE<BadgeSet[]>("get_global_chat_badges"),
	getChannelChatBadges: (params: GetChannelChatBadgesParams) => __TAURI_INVOKE<BadgeSet[]>("get_channel_chat_badges", { params }),
	deleteChatMessages: (params: DeleteChatMessagesParams) => __TAURI_INVOKE<null>("delete_chat_messages", { params }),
	banUser: (params: BanUserParams) => __TAURI_INVOKE<Ban>("ban_user", { params }),
	unbanUser: (params: UnbanUserParams) => __TAURI_INVOKE<null>("unban_user", { params }),
	getBannedUsers: (params: GetBannedUsersParams) => __TAURI_INVOKE<PaginatedResponse<BannedUser>>("get_banned_users", { params }),
	getModerators: (params: GetModeratorsParams) => __TAURI_INVOKE<PaginatedResponse<UserRef>>("get_moderators", { params }),
	getModeratedChannels: () => __TAURI_INVOKE<UserRef[]>("get_moderated_channels"),
	warnUser: (params: WarnUserParams) => __TAURI_INVOKE<null>("warn_user", { params }),
	manageHeldAutomodMessage: (params: ManageHeldAutomodMessageParams) => __TAURI_INVOKE<null>("manage_held_automod_message", { params }),
	addChannelVip: (params: ChannelVipParams) => __TAURI_INVOKE<null>("add_channel_vip", { params }),
	removeChannelVip: (params: ChannelVipParams) => __TAURI_INVOKE<null>("remove_channel_vip", { params }),
	startRaid: (params: StartRaidParams) => __TAURI_INVOKE<null>("start_raid", { params }),
	cancelRaid: (params: CancelRaidParams) => __TAURI_INVOKE<null>("cancel_raid", { params }),
	createClip: (params: CreateClipParams) => __TAURI_INVOKE<CreatedClip>("create_clip", { params }),
	getChannelInformation: (params: GetChannelInformationParams) => __TAURI_INVOKE<ChannelInfo[]>("get_channel_information", { params }),
	getChannelFollowers: (params: GetChannelFollowersParams) => __TAURI_INVOKE<PaginatedResponse<Follow>>("get_channel_followers", { params }),
	getFollowedChannels: (params: GetFollowedChannelsParams) => __TAURI_INVOKE<Follow[]>("get_followed_channels", { params }),
	modifyChannelInformation: (params: ModifyChannelInformationParams) => __TAURI_INVOKE<null>("modify_channel_information", { params }),
	startCommercial: (params: StartCommercialParams) => __TAURI_INVOKE<null>("start_commercial", { params }),
	bttvGetGlobalEmotes: () => __TAURI_INVOKE<EmoteEntry[]>("bttv_get_global_emotes"),
	bttvGetChannelEmotes: (params: ChannelIdParams) => __TAURI_INVOKE<EmoteEntry[]>("bttv_get_channel_emotes", { params }),
	ffzGetGlobalEmotes: () => __TAURI_INVOKE<EmoteEntry[]>("ffz_get_global_emotes"),
	ffzGetChannelEmotes: (params: ChannelLoginParams) => __TAURI_INVOKE<EmoteEntry[]>("ffz_get_channel_emotes", { params }),
	seventvGetGlobalEmotes: () => __TAURI_INVOKE<EmoteEntry[]>("seventv_get_global_emotes"),
	seventvGetChannelEmotes: (params: ChannelIdParams) => __TAURI_INVOKE<ChannelResult>("seventv_get_channel_emotes", { params }),
	seventvSubscribeEmoteSet: (params: EmoteSetParams) => __TAURI_INVOKE<void>("seventv_subscribe_emote_set", { params }),
	seventvUnsubscribeEmoteSet: (params: EmoteSetParams) => __TAURI_INVOKE<void>("seventv_unsubscribe_emote_set", { params }),
	getRecentMessages: (params: GetRecentMessagesParams) => __TAURI_INVOKE<RecentMessage[]>("get_recent_messages", { params }),
	readKeymap: () => __TAURI_INVOKE<string>("read_keymap"),
	writeKeymap: (params: WriteKeymapParams) => __TAURI_INVOKE<null>("write_keymap", { params }),
	watchSetMuted: (params: SetMutedParams) => __TAURI_INVOKE<null>("watch_set_muted", { params }),
	watchRequestState: () => __TAURI_INVOKE<null>("watch_request_state"),
	setMentionsBadge: (count: number, iconBytes: number[] | null) => __TAURI_INVOKE<null>("set_mentions_badge", { count, iconBytes }),
};

/** Events */
export const events = {
	authFailed: makeEvent<AuthFailed>("auth-failed"),
	authSucceeded: makeEvent<AuthSucceeded>("auth-succeeded"),
	emoteSetUpdated: makeEvent<EmoteSetUpdated>("emote-set-updated"),
	eventSubConnection: makeEvent<EventSubConnection>("event-sub-connection"),
	eventSubFailed: makeEvent<EventSubFailed>("event-sub-failed"),
	eventSubRecovered: makeEvent<EventSubRecovered>("event-sub-recovered"),
	eventSubSubscription: makeEvent<EventSubSubscription>("event-sub-subscription"),
	watchDisconnected: makeEvent<WatchDisconnected>("watch-disconnected"),
	watchState: makeEvent<WatchState>("watch-state"),
};

/* Constants */
export const EVENTSUB_EVENT_NAMES = {"automod.message.hold":"automod-message-hold","automod.message.update":"automod-message-update","channel.channel_points_custom_reward_redemption.add":"channel-points-redemption-add","channel.chat.clear":"channel-chat-clear","channel.chat.clear_user_messages":"channel-chat-clear-user-messages","channel.chat.message":"channel-chat-message","channel.chat.message_delete":"channel-chat-message-delete","channel.chat.notification":"channel-chat-notification","channel.follow":"channel-follow","channel.moderate":"channel-moderate","channel.shoutout.create":"channel-shoutout-create"} as const;

/* Types */
export type ActivityInput = {
	details?: string | null,
	detailsUrl?: string | null,
	stateText?: string | null,
	stateUrl?: string | null,
	largeImage?: string | null,
	largeText?: string | null,
	largeUrl?: string | null,
	smallImage?: string | null,
	smallText?: string | null,
	startedAt?: number | null,
	activityType?: ActivityType | null,
	statusDisplayType?: StatusDisplayType | null,
	buttons?: Button[] | null,
};

export type ActivityType = "playing" | "listening" | "watching" | "competing";

export type AnnouncementColor = "primary" | "blue" | "green" | "orange" | "purple";

export type AuthFailed = Error;

export type AuthSucceeded = User;

export type AutomodAction = "allow" | "deny";

export type Badge = {
	id: string,
	url1x: string,
	url2x: string,
	url4x: string,
	title: string,
	description: string,
};

export type BadgeSet = {
	setId: string,
	versions: Badge[],
};

export type Ban = {
	userId: UserId,
	broadcasterId: UserId,
	moderatorId: UserId,
	createdAt: string,
	endTime: string,
};

export type BanUserParams = {
	broadcasterId: UserId,
	userId: UserId,
	duration?: number | null,
	reason?: string | null,
};

export type BannedUser = {
	user: UserRef,
	moderator: UserRef,
	reason: string,
	expiresAt: string,
};

export type BroadcasterType = "normal" | "affiliate" | "partner";

export type Button = {
	label: string,
	url: string,
};

export type CancelRaidParams = {
	broadcasterId: UserId,
};

export type Category = {
	id: string,
	name: string,
	boxArtUrl: string,
};

export type ChannelIdParams = {
	channelId: string,
};

export type ChannelInfo = {
	broadcaster: UserRef,
	game: GameRef,
	title: string,
};

export type ChannelLoginParams = {
	channelLogin: string,
};

export type ChannelResult = {
	emotes: EmoteEntry[],
	emote_set_id: string | null,
};

export type ChannelVipParams = {
	broadcasterId: UserId,
	userId: UserId,
};

export type ChatColor = "blue" | "blue_violet" | "cadet_blue" | "chocolate" | "coral" | "dodger_blue" | "firebrick" | "golden_rod" | "green" | "hot_pink" | "orange_red" | "red" | "sea_green" | "spring_green" | "yellow_green";

export type ChatterBadge = {
	set_id: string,
	id: string,
	info: string,
};

export type CreateClipParams = {
	broadcasterId: UserId,
	title?: string | null,
	duration?: number | null,
};

export type CreateStreamMarkerParams = {
	description?: string | null,
};

export type CreatedClip = {
	id: string,
};

export type DcfAuthResponse = {
	user_code: string,
	verification_uri: string,
};

export type DeleteChatMessagesParams = {
	broadcasterId: UserId,
	messageId?: MessageId | null,
};

export type DiscordConnectParams = {
	clientId?: string | null,
};

export type Emote = {
	id: string,
	name: string,
	url: string,
};

export type EmoteEntry = {
	name: string,
	url: string,
};

export type EmoteRef = {
	id: string,
};

export type EmoteSetParams = {
	emoteSetId: string,
};

export type EmoteSetUpdated = {
	id: string,
	actor: string | null,
	added: EmoteEntry[],
	removed: string[],
	renamed: Rename[],
};

export type Error = { kind: "notAuthenticated" } | { kind: "helix"; message: {
	status: number,
	message: string,
} } | { kind: "http"; message: string } | { kind: "auth"; message: string } | { kind: "keyring"; message: string } | { kind: "discord"; message: string } | { kind: "io"; message: string } | { kind: "invalid"; message: string };

export type EventKind = "channel.chat.message" | "channel.chat.notification" | "channel.chat.message_delete" | "channel.chat.clear" | "channel.chat.clear_user_messages" | "channel.shoutout.create" | "channel.follow" | "channel.moderate" | "automod.message.hold" | "automod.message.update" | "channel.channel_points_custom_reward_redemption.add";

export type EventSubConnection = {
	connected: boolean,
};

export type EventSubFailed = Error;

export type EventSubRecovered = {
	since: number,
	broadcasterIds: UserId[],
};

export type EventSubSubscription = {
	broadcasterId: UserId,
	kind: EventKind,
	status: SubscriptionStatus,
};

export type Follow = {
	user: UserRef,
	followedAt: string,
};

export type GameId = string;

export type GameRef = {
	id: GameId,
	name: string,
};

export type GetBannedUsersParams = {
	broadcasterId: UserId,
	userId?: UserId | null,
	first?: number | null,
	after?: string | null,
};

export type GetChannelChatBadgesParams = {
	broadcasterId: UserId,
};

export type GetChannelFollowersParams = {
	broadcasterId: UserId,
	userId?: UserId | null,
	first?: number | null,
	after?: string | null,
};

export type GetChannelInformationParams = {
	broadcasterIds: UserId[],
};

export type GetFollowedChannelsParams = {
	userId: UserId,
	broadcasterId?: UserId | null,
};

export type GetModeratorsParams = {
	broadcasterId: UserId,
	first?: number | null,
	after?: string | null,
};

export type GetRecentMessagesParams = {
	channelLogin: string,
	limit?: number | null,
	after?: number | null,
};

export type GetStreamsFromIdsParams = {
	userIds: UserId[],
};

export type GetStreamsParams = {
	userIds?: UserId[],
	userLogins?: string[],
	gameIds?: GameId[],
	language?: string | null,
	first?: number | null,
	after?: string | null,
	before?: string | null,
};

export type GetUsersParams = {
	ids?: UserId[],
	logins?: string[],
};

export type ManageHeldAutomodMessageParams = {
	msgId: MessageId,
	action: AutomodAction,
};

export type MentionRef = {
	user_login: string,
};

export type MessageBody = {
	text: string,
	fragments: MessageFragment[],
};

export type MessageFragment = { type: "text"; text: string } | { type: "emote"; text: string; emote: EmoteRef } | { type: "mention"; text: string; mention: MentionRef };

export type MessageId = string;

export type ModifyChannelInformationParams = {
	broadcasterId: UserId,
	title?: string | null,
	gameId?: GameId | null,
};

export type PaginatedResponse<T> = {
	data: T[],
	pagination: Pagination,
};

export type Pagination = {
	cursor: string | null,
};

export type RecentMessage = {
	broadcaster_user_id: string,
	message_id: string,
	chatter_user_id: string,
	chatter_user_login: string,
	chatter_user_name: string,
	color: string,
	message: MessageBody,
	message_type: string,
	badges: ChatterBadge[],
	reply: Reply | null,
	channel_points_custom_reward_id: string | null,
	timestamp_ms: number,
	deleted: boolean,
};

export type Rename = {
	from: string,
	to: string,
};

export type Reply = {
	parent_message_id: string,
	parent_message_body: string,
	parent_user_name: string,
	parent_user_login: string,
	parent_user_id: string,
};

export type SearchCategoriesParams = {
	query?: string,
	first?: number | null,
};

export type SearchChannel = {
	user: UserRef,
	gameName: string,
	title: string,
	isLive: boolean,
	profileImageUrl: string,
	startedAt: string,
};

export type SearchChannelsParams = {
	query: string,
	liveOnly?: boolean,
	first?: number | null,
};

export type SendChatAnnouncementParams = {
	broadcasterId: UserId,
	message: string,
	color?: AnnouncementColor,
};

export type SendChatMessageParams = {
	broadcasterId: UserId,
	message: string,
	replyParentMessageId?: MessageId | null,
};

export type SendMessageResult = {
	messageId: string | null,
	isSent: boolean,
	/**  AutoMod is holding the message for a moderator to approve or deny. */
	held: boolean,
	dropReason: string | null,
};

export type SendShoutoutParams = {
	fromBroadcasterId: UserId,
	toBroadcasterId: UserId,
};

export type SetMutedParams = {
	channel: string,
	muted: boolean,
};

export type StartCommercialParams = {
	broadcasterId: UserId,
	length: number,
};

export type StartRaidParams = {
	fromBroadcasterId: UserId,
	toBroadcasterId: UserId,
};

export type StatusDisplayType = "name" | "state" | "details";

export type Stream = {
	id: StreamId,
	user: UserRef,
	game: GameRef,
	title: string,
	viewerCount: number,
	startedAt: string,
	language: string,
	thumbnail: Thumbnail,
	tags: string[],
	isMature: boolean,
};

export type StreamId = string;

export type SubscribeParams = {
	broadcasterId: string,
	kind: EventKind,
};

export type SubscriptionStatus = { type: "subscribed" } | { type: "unsubscribed" } | { type: "failed"; error: string };

export type Thumbnail = {
	small: string,
	medium: string,
	large: string,
};

export type UnbanUserParams = {
	broadcasterId: UserId,
	userId: UserId,
};

export type UpdateChatSettingsParams = {
	broadcasterId: UserId,
	emoteMode?: boolean | null,
	followerMode?: boolean | null,
	followerModeDuration?: number | null,
	slowMode?: boolean | null,
	slowModeWaitTime?: number | null,
	subscriberMode?: boolean | null,
	uniqueChatMode?: boolean | null,
};

export type UpdateUserChatColorParams = {
	color: ChatColor,
};

export type User = {
	id: UserId,
	login: string,
	displayName: string,
	description: string,
	profileImageUrl: string,
	broadcasterType: BroadcasterType,
	createdAt: string,
};

export type UserEmote = {
	id: string,
	name: string,
	url: string,
	emoteType: string,
	emoteSetId: string,
	ownerId: UserId,
};

export type UserId = string;

export type UserRef = {
	id: UserId,
	login: string,
	displayName: string,
};

export type WarnUserParams = {
	broadcasterId: UserId,
	userId: UserId,
	reason: string,
};

export type WatchChannel = {
	login: string,
	muted?: boolean,
};

export type WatchDisconnected = null;

export type WatchState = {
	channels: WatchChannel[],
	current: string | null,
};

export type WriteKeymapParams = {
	contents: string,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

