name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            args: ""
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: setup rust
        uses: dtolnay/rust-toolchain@stable

      - name: rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: install frontend deps
        run: npm install

      - name: build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "Deatch ${{ github.ref_name }}"
          releaseDraft: false
          prerelease: false
          updaterJsonPreferNsis: false
          args: ${{ matrix.args }}
